### ISSUE TITLE
Has this ended or can applications still be submitted

### ISSUE THREAD

**Issue by rifse** [woltapp/engineering-summer-intern-2022#2]
Given that both Helsinki and Berlin links lead to non-existing posts I suspect you are not accepting any more applications.
Am I right?

**Comment by jerry-git** [comment]
Hey! That's correct indeed. I added a note in the readme 🙂  https://github.com/woltapp/engineering-summer-intern-2022/commit/ada9c745882074f6577ed397ee40b2b40c7c37d7.
